import MSPCodes from "../msp/MSPCodes";
import { REQUIRED_RESPONSE_LENGTHS } from "./SnapshotContract";

// Reads used by the configuration tabs. Never infer reads from numeric ranges:
// several MSP commands in those ranges perform writes or calibration.
const names =
    `MSP_API_VERSION MSP_FC_VARIANT MSP_FC_VERSION MSP_BOARD_INFO MSP_BUILD_INFO MSP_STATUS MSP_STATUS_EX MSP_UID
MSP_FEATURE_CONFIG MSP_BEEPER_CONFIG MSP_ARMING_CONFIG MSP_SENSOR_CONFIG MSP_RX_CONFIG MSP_CF_SERIAL_CONFIG
MSP_MODE_RANGES MSP_MODE_RANGES_EXTRA MSP_ADJUSTMENT_RANGES MSP_RC_TUNING MSP_PID MSP_PID_ADVANCED MSP_FILTER_CONFIG
MSP_MOTOR_CONFIG MSP_ADVANCED_CONFIG MSP_MIXER_CONFIG MSP_FAILSAFE_CONFIG MSP_BATTERY_CONFIG MSP_VOLTAGE_METERS
MSP_CURRENT_METERS MSP_CURRENT_METER_CONFIG MSP_VOLTAGE_METER_CONFIG MSP_OSD_CONFIG MSP_VTX_CONFIG MSP_LED_STRIP_CONFIG
MSP_LED_COLORS MSP_LED_STRIP_MODECOLOR MSP_BLACKBOX_CONFIG MSP_DATAFLASH_SUMMARY MSP_SDCARD_SUMMARY MSP_GPS_CONFIG MSP_GPS_RESCUE
MSP_PIDNAMES MSP_RC_DEADBAND MSP_SIMPLIFIED_TUNING MSP_VALIDATE_SIMPLIFIED_TUNING MSP_BOARD_ALIGNMENT_CONFIG MSP_ACC_TRIM MSP_SENSOR_ALIGNMENT
MSP_RX_MAP MSP_RSSI_CONFIG MSP_RXFAIL_CONFIG MSP_MOTOR_3D_CONFIG MSP_SERVO_CONFIGURATIONS MSP_SERVO_MIX_RULES
MSP_COMPASS_CONFIG MSP2_SENSOR_CONFIG_ACTIVE MSP2_GYRO_SENSOR MSP2_MCU_INFO MSP2_MOTOR_OUTPUT_REORDERING MSP2_GET_VTX_DEVICE_STATUS
MSP_ANALOG MSP_BATTERY_STATE MSP_BOXNAMES MSP_BOXIDS MSP_RAW_GPS MSP_COMP_GPS MSP_GPS_SV_INFO MSP_RAW_IMU MSP_ATTITUDE
MSP_ATTITUDE_QUATERNION MSP_ALTITUDE MSP_SONAR MSP_RC MSP_MOTOR MSP_SERVO MSP_MOTOR_TELEMETRY MSP_OSD_CANVAS MSP_DEBUG MSP2_GET_LED_STRIP_CONFIG_VALUES MSP2_COMMON_SERIAL_CONFIG`.split(
            /\s+/,
        );

export const STATIC_SNAPSHOT_CODES = [...new Set(names.map((name) => MSPCodes[name]).filter(Number.isInteger))];
const readCodes = new Set([
    ...STATIC_SNAPSHOT_CODES,
    MSPCodes.MSP_NAME,
    MSPCodes.MSP2_GET_TEXT,
    MSPCodes.MSP_VTXTABLE_BAND,
    MSPCodes.MSP_VTXTABLE_POWERLEVEL,
]);
export const isSnapshotReadCode = (code) => readCodes.has(code);
export const isSnapshotRequiredCode = (code) => Object.hasOwn(REQUIRED_RESPONSE_LENGTHS, code);
